# Auto-generated by ros2_systemd_manager
# Re-generate with: make update

SUDO ?= sudo
SCRIPT ?= ros2-systemd-manager
CONFIG ?=
WORKSPACE_KEY := default_ws
UNITS := ros2-foxglove-bridge.service ros2-soem-bringup.service ros2-infantry-chassis.service
GENERATED_MK := $(lastword $(MAKEFILE_LIST))

EFFECTIVE_SCRIPT := $(if $(strip $(SCRIPT)),$(SCRIPT),ros2-systemd-manager)
EFFECTIVE_CONFIG := $(if $(strip $(CONFIG)),$(CONFIG),$(firstword $(wildcard ./ros2_services.yaml ./*.yaml)))

.PHONY: help ensure-config install apply uninstall start stop restart status enable disable logs logs-recent update makefile start-ros2-foxglove-bridge stop-ros2-foxglove-bridge restart-ros2-foxglove-bridge status-ros2-foxglove-bridge enable-ros2-foxglove-bridge disable-ros2-foxglove-bridge logs-ros2-foxglove-bridge logs-recent-ros2-foxglove-bridge start-ros2-soem-bringup stop-ros2-soem-bringup restart-ros2-soem-bringup status-ros2-soem-bringup enable-ros2-soem-bringup disable-ros2-soem-bringup logs-ros2-soem-bringup logs-recent-ros2-soem-bringup start-ros2-infantry-chassis stop-ros2-infantry-chassis restart-ros2-infantry-chassis status-ros2-infantry-chassis enable-ros2-infantry-chassis disable-ros2-infantry-chassis logs-ros2-infantry-chassis logs-recent-ros2-infantry-chassis

help:
	@echo "Targets:"
	@echo "  make install                # install unit files only"
	@echo "  make apply                  # install + start + enable"
	@echo "  make start                  # systemctl start all configured units"
	@echo "  make stop                   # systemctl stop all configured units"
	@echo "  make restart                # systemctl restart all configured units"
	@echo "  make status                 # systemctl status all configured units"
	@echo "  make enable                 # systemctl enable all configured units"
	@echo "  make disable                # systemctl disable all configured units"
	@echo "  make logs                   # follow logs for all configured units"
	@echo "  make logs-recent            # show last 200 log lines for all configured units"
	@echo "  make <op>-<service>         # op in start/stop/restart/status/enable/disable/logs/logs-recent"
	@echo "  make uninstall              # uninstall all configured units"
	@echo "  make update                 # stop old + uninstall removed + install/start/enable + refresh generated mk"
	@echo "  make makefile               # refresh generated mk only (no systemd changes)"
	@echo "  make <target> CONFIG=./file.yaml  # override auto-discovered yaml"

ensure-config:
	@if [ -z "$(EFFECTIVE_CONFIG)" ]; then \
		echo "ERROR: no yaml config found in current directory (expected ./ros2_services.yaml or ./*.yaml)."; \
		exit 1; \
	fi

install: ensure-config
	$(SUDO) $(EFFECTIVE_SCRIPT) install --config "$(EFFECTIVE_CONFIG)" --workspace-key "$(WORKSPACE_KEY)"

apply: ensure-config
	$(SUDO) $(EFFECTIVE_SCRIPT) apply --config "$(EFFECTIVE_CONFIG)" --workspace-key "$(WORKSPACE_KEY)"

uninstall: ensure-config
	$(SUDO) $(EFFECTIVE_SCRIPT) uninstall --config "$(EFFECTIVE_CONFIG)" --workspace-key "$(WORKSPACE_KEY)"

start:
	$(SUDO) systemctl start $(UNITS)

stop:
	$(SUDO) systemctl stop $(UNITS)

restart:
	$(SUDO) systemctl restart $(UNITS)

status:
	$(SUDO) systemctl status $(UNITS)

enable:
	$(SUDO) systemctl enable $(UNITS)

disable:
	$(SUDO) systemctl disable $(UNITS)

logs:
	$(SUDO) journalctl $(foreach u,$(UNITS),-u $(u)) -f

logs-recent:
	$(SUDO) journalctl $(foreach u,$(UNITS),-u $(u)) -n 200 --no-pager

update: ensure-config
	$(SUDO) $(EFFECTIVE_SCRIPT) update --config "$(EFFECTIVE_CONFIG)" --workspace-key "$(WORKSPACE_KEY)" --previous-makefile "$(GENERATED_MK)"

makefile: ensure-config
	$(EFFECTIVE_SCRIPT) makefile --config "$(EFFECTIVE_CONFIG)" --workspace-key "$(WORKSPACE_KEY)"


start-ros2-foxglove-bridge:
	$(SUDO) systemctl start "ros2-foxglove-bridge.service"

stop-ros2-foxglove-bridge:
	$(SUDO) systemctl stop "ros2-foxglove-bridge.service"

restart-ros2-foxglove-bridge:
	$(SUDO) systemctl restart "ros2-foxglove-bridge.service"

status-ros2-foxglove-bridge:
	$(SUDO) systemctl status "ros2-foxglove-bridge.service"

enable-ros2-foxglove-bridge:
	$(SUDO) systemctl enable "ros2-foxglove-bridge.service"

disable-ros2-foxglove-bridge:
	$(SUDO) systemctl disable "ros2-foxglove-bridge.service"

logs-ros2-foxglove-bridge:
	$(SUDO) journalctl -u "ros2-foxglove-bridge.service" -n 100 -f

logs-recent-ros2-foxglove-bridge:
	$(SUDO) journalctl -u "ros2-foxglove-bridge.service" -n 200 --no-pager


start-ros2-soem-bringup:
	$(SUDO) systemctl start "ros2-soem-bringup.service"

stop-ros2-soem-bringup:
	$(SUDO) systemctl stop "ros2-soem-bringup.service"

restart-ros2-soem-bringup:
	$(SUDO) systemctl restart "ros2-soem-bringup.service"

status-ros2-soem-bringup:
	$(SUDO) systemctl status "ros2-soem-bringup.service"

enable-ros2-soem-bringup:
	$(SUDO) systemctl enable "ros2-soem-bringup.service"

disable-ros2-soem-bringup:
	$(SUDO) systemctl disable "ros2-soem-bringup.service"

logs-ros2-soem-bringup:
	$(SUDO) journalctl -u "ros2-soem-bringup.service" -n 100 -f

logs-recent-ros2-soem-bringup:
	$(SUDO) journalctl -u "ros2-soem-bringup.service" -n 200 --no-pager


start-ros2-infantry-chassis:
	$(SUDO) systemctl start "ros2-infantry-chassis.service"

stop-ros2-infantry-chassis:
	$(SUDO) systemctl stop "ros2-infantry-chassis.service"

restart-ros2-infantry-chassis:
	$(SUDO) systemctl restart "ros2-infantry-chassis.service"

status-ros2-infantry-chassis:
	$(SUDO) systemctl status "ros2-infantry-chassis.service"

enable-ros2-infantry-chassis:
	$(SUDO) systemctl enable "ros2-infantry-chassis.service"

disable-ros2-infantry-chassis:
	$(SUDO) systemctl disable "ros2-infantry-chassis.service"

logs-ros2-infantry-chassis:
	$(SUDO) journalctl -u "ros2-infantry-chassis.service" -n 100 -f

logs-recent-ros2-infantry-chassis:
	$(SUDO) journalctl -u "ros2-infantry-chassis.service" -n 200 --no-pager
