from pathlib import Path
import sys
from typing import Any, Dict, List, Tuple

from .config import resolve_makefile_path
from .runtime import err, log


def build_makefile_content(
    *,
    script_default: str,
    config_default: str,
    workspace_key: str,
    unit_names: List[str],
) -> str:
    """Build Makefile content for service lifecycle operations."""
    quoted_units = " ".join(unit_names)

    service_entries: List[Tuple[str, str]] = []
    seen_service_keys = set()
    for unit_name in unit_names:
        service_key = unit_name[:-
                                8] if unit_name.endswith(".service") else unit_name
        if service_key in seen_service_keys:
            continue
        seen_service_keys.add(service_key)
        service_entries.append((service_key, unit_name))

    per_service_targets: List[str] = []
    per_service_blocks: List[str] = []

    for service_key, unit_name in service_entries:
        per_service_targets.extend(
            [
                f"start-{service_key}",
                f"stop-{service_key}",
                f"restart-{service_key}",
                f"status-{service_key}",
                f"enable-{service_key}",
                f"disable-{service_key}",
                f"logs-{service_key}",
                f"logs-recent-{service_key}",
                f"logs-static-{service_key}",
            ]
        )

        per_service_blocks.append(
            f"""
start-{service_key}:
\t$(SUDO) systemctl start \"{unit_name}\"

stop-{service_key}:
\t$(SUDO) systemctl stop \"{unit_name}\"

restart-{service_key}:
\t$(SUDO) systemctl restart \"{unit_name}\"

status-{service_key}:
\t$(SUDO) systemctl status \"{unit_name}\"

enable-{service_key}:
\t$(SUDO) systemctl enable \"{unit_name}\"

disable-{service_key}:
\t$(SUDO) systemctl disable \"{unit_name}\"

logs-{service_key}:
\t$(SUDO) journalctl -u \"{unit_name}\" -n 100 -f

logs-recent-{service_key}:
\t$(SUDO) journalctl -u \"{unit_name}\" -n 200 --no-pager

logs-static-{service_key}:
\t$(SUDO) journalctl -u \"{unit_name}\" -n 200 --no-pager
""".rstrip()
        )

    phony_targets = " ".join(
        [
            "help",
            "install-only",
            "install-start-enable",
            "uninstall",
            "start",
            "stop",
            "restart",
            "status",
            "enable",
            "disable",
            "logs",
            "logs-follow",
            "update",
            "update-makefile",
            *per_service_targets,
        ]
    )

    per_service_blocks_text = "\n\n".join(per_service_blocks)

    return f"""# Auto-generated by ros2_systemd_manager.py
# Re-generate with: make update

PYTHON ?= python3
SUDO ?= sudo
SCRIPT ?= {script_default}
CONFIG ?= {config_default}
WORKSPACE_KEY := {workspace_key}
UNITS := {quoted_units}

EFFECTIVE_SCRIPT := $(if $(strip $(SCRIPT)),$(SCRIPT),{script_default})
EFFECTIVE_CONFIG := $(if $(strip $(CONFIG)),$(CONFIG),{config_default})

.PHONY: {phony_targets}

help:
\t@echo \"Targets:\"
\t@echo \"  make install-only           # install unit files only\"
\t@echo \"  make install-start-enable   # install + start + enable\"
\t@echo \"  make start                  # systemctl start all configured units\"
\t@echo \"  make stop                   # systemctl stop all configured units\"
\t@echo \"  make restart                # systemctl restart all configured units\"
\t@echo \"  make status                 # systemctl status all configured units\"
\t@echo \"  make enable                 # systemctl enable all configured units\"
\t@echo \"  make disable                # systemctl disable all configured units\"
\t@echo \"  make logs                   # show last 200 log lines for all configured units\"
\t@echo \"  make logs-follow            # follow logs for all configured units\"
\t@echo \"  make <op>-<service>         # op in start/stop/restart/status/enable/disable/logs\"
\t@echo \"  make logs-recent-<service>  # show last 200 log lines for one service\"
\t@echo \"  make logs-static-<service>  # alias of logs-recent-<service>\"
\t@echo \"  make uninstall              # uninstall all configured units\"
\t@echo \"  make update                 # stop old + uninstall removed + install/start/enable + refresh Makefile\"
\t@echo \"  make update-makefile        # refresh Makefile only (no systemd changes)\"

install-only:
\t$(SUDO) $(PYTHON) \"$(EFFECTIVE_SCRIPT)\" install-only --config \"$(EFFECTIVE_CONFIG)\" --workspace-key \"$(WORKSPACE_KEY)\"

install-start-enable:
\t$(SUDO) $(PYTHON) \"$(EFFECTIVE_SCRIPT)\" install-start-enable --config \"$(EFFECTIVE_CONFIG)\" --workspace-key \"$(WORKSPACE_KEY)\"

uninstall:
\t$(SUDO) $(PYTHON) \"$(EFFECTIVE_SCRIPT)\" uninstall --config \"$(EFFECTIVE_CONFIG)\" --workspace-key \"$(WORKSPACE_KEY)\"

start:
\t$(SUDO) systemctl start $(UNITS)

stop:
\t$(SUDO) systemctl stop $(UNITS)

restart:
\t$(SUDO) systemctl restart $(UNITS)

status:
\t$(SUDO) systemctl status $(UNITS)

enable:
\t$(SUDO) systemctl enable $(UNITS)

disable:
\t$(SUDO) systemctl disable $(UNITS)

logs:
\t$(SUDO) journalctl $(foreach u,$(UNITS),-u $(u)) -n 200 --no-pager

logs-follow:
\t$(SUDO) journalctl $(foreach u,$(UNITS),-u $(u)) -f

update:
\t$(SUDO) $(PYTHON) \"$(EFFECTIVE_SCRIPT)\" sync-update --config \"$(EFFECTIVE_CONFIG)\" --workspace-key \"$(WORKSPACE_KEY)\" --previous-makefile \"$(firstword $(MAKEFILE_LIST))\"

update-makefile:
\t$(PYTHON) \"$(EFFECTIVE_SCRIPT)\" update-makefile --config \"$(EFFECTIVE_CONFIG)\" --workspace-key \"$(WORKSPACE_KEY)\"

{per_service_blocks_text}
"""


def write_makefile(config: Dict[str, Any], config_path: Path, workspace_key: str) -> Path:
    """Generate (or overwrite) Makefile based on YAML workspace services."""
    workspace_cfg = config["workspaces"][workspace_key]
    services = workspace_cfg.get("services", [])
    unit_names = [svc["unit_name"] for svc in services]

    if not unit_names:
        err(f"workspace {workspace_key} has an empty services list; cannot build Makefile units.")
        sys.exit(1)

    output_path = resolve_makefile_path(config, config_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    output_path_raw = str(config.get("makefile", {}).get(
        "output_path", "Makefile")).strip()
    output_path_rel = Path(output_path_raw)
    is_local_makefile = (
        not output_path_rel.is_absolute()
        and output_path_rel.name == "Makefile"
        and output_path_rel.parent in (Path("."), Path(""))
    )

    if is_local_makefile:
        script_default = "./ros2_systemd_manager.py"
        config_default = "./ros2_services.yaml"
    else:
        script_default = str(Path(sys.argv[0]).resolve())
        config_default = str(config_path.resolve())

    content = build_makefile_content(
        script_default=script_default,
        config_default=config_default,
        workspace_key=workspace_key,
        unit_names=unit_names,
    )

    output_path.write_text(content, encoding="utf-8")
    log(f"Makefile generated: {output_path}")
    return output_path
