from pathlib import Path
import re
import sys
from typing import Any, Dict, List, Tuple

from .config import resolve_makefile_path
from .runtime import err, log


AUTO_GENERATED_HEADER = "# Auto-generated by ros2_systemd_manager"
AUTO_INCLUDE_COMMENT = "# Auto-added by ros2_systemd_manager"


def _pick_main_makefile_path(base_dir: Path) -> Path:
    makefile_path = base_dir / "Makefile"
    lowercase_path = base_dir / "makefile"
    if makefile_path.exists():
        return makefile_path
    if lowercase_path.exists():
        return lowercase_path
    return makefile_path


def _ensure_main_makefile_includes_fragment(base_dir: Path, fragment_name: str) -> None:
    main_makefile = _pick_main_makefile_path(base_dir)
    include_line = f"include {fragment_name}"

    if main_makefile.exists():
        original_text = main_makefile.read_text(encoding="utf-8")
    else:
        original_text = ""

    # If old generated body is still present in main Makefile, strip it.
    cleaned_text = original_text
    lines = cleaned_text.splitlines()
    for idx, line in enumerate(lines):
        if line.strip() == AUTO_GENERATED_HEADER:
            prelude = lines[:idx]
            if all(
                (not item.strip())
                or item.strip().startswith("include ")
                or item.strip().startswith(AUTO_INCLUDE_COMMENT)
                for item in prelude
            ):
                cleaned_text = "\n".join(prelude)
            break

    include_re = re.compile(
        rf"^\s*-?include\s+{re.escape(fragment_name)}\s*$",
        flags=re.MULTILINE,
    )
    if include_re.search(cleaned_text):
        if cleaned_text != original_text:
            if cleaned_text and not cleaned_text.endswith("\n"):
                cleaned_text += "\n"
            main_makefile.write_text(cleaned_text, encoding="utf-8")
            log(
                f"Cleaned legacy generated body from main Makefile: {main_makefile}")
        return

    header_lines = [include_line,
                    f"{AUTO_INCLUDE_COMMENT}: include generated targets", ""]
    new_text = "\n".join(header_lines) + cleaned_text
    main_makefile.write_text(new_text, encoding="utf-8")
    log(f"Updated main Makefile include: {main_makefile}")


def _migrate_legacy_auto_generated_makefile(base_dir: Path, target_fragment_path: Path) -> None:
    if target_fragment_path.exists():
        return

    main_makefile = _pick_main_makefile_path(base_dir)
    if not main_makefile.exists():
        return

    makefile_text = main_makefile.read_text(encoding="utf-8")
    first_line = makefile_text.splitlines()[0].strip(
    ) if makefile_text.splitlines() else ""
    if first_line != AUTO_GENERATED_HEADER:
        return

    target_fragment_path.parent.mkdir(parents=True, exist_ok=True)
    target_fragment_path.write_text(makefile_text, encoding="utf-8")
    log(f"Migrated legacy auto-generated Makefile to: {target_fragment_path}")

    # Remove old generated content from main Makefile; it will be re-linked via include.
    main_makefile.write_text("", encoding="utf-8")


def build_makefile_content(
    *,
    script_default: str,
    workspace_key: str,
    unit_names: List[str],
) -> str:
    """Build Makefile content for service lifecycle operations."""
    quoted_units = " ".join(unit_names)

    service_entries: List[Tuple[str, str]] = []
    seen_service_keys = set()
    for unit_name in unit_names:
        service_key = unit_name[:-
                                8] if unit_name.endswith(".service") else unit_name
        if service_key in seen_service_keys:
            continue
        seen_service_keys.add(service_key)
        service_entries.append((service_key, unit_name))

    per_service_targets: List[str] = []
    per_service_blocks: List[str] = []

    for service_key, unit_name in service_entries:
        per_service_targets.extend(
            [
                f"start-{service_key}",
                f"stop-{service_key}",
                f"restart-{service_key}",
                f"status-{service_key}",
                f"enable-{service_key}",
                f"disable-{service_key}",
                f"logs-{service_key}",
                f"logs-recent-{service_key}",
            ]
        )

        per_service_blocks.append(
            f"""
start-{service_key}:
\t$(SUDO) systemctl start \"{unit_name}\"

stop-{service_key}:
\t$(SUDO) systemctl stop \"{unit_name}\"

restart-{service_key}:
\t$(SUDO) systemctl restart \"{unit_name}\"

status-{service_key}:
\t$(SUDO) systemctl status \"{unit_name}\"

enable-{service_key}:
\t$(SUDO) systemctl enable \"{unit_name}\"

disable-{service_key}:
\t$(SUDO) systemctl disable \"{unit_name}\"

logs-{service_key}:
\t$(SUDO) journalctl -u \"{unit_name}\" -n 100 -f

logs-recent-{service_key}:
\t$(SUDO) journalctl -u \"{unit_name}\" -n 200 --no-pager
""".rstrip()
        )

    phony_targets = " ".join(
        [
            "help",
            "upgrade",
            "ensure-config",
            "install",
            "apply",
            "uninstall",
            "start",
            "stop",
            "restart",
            "status",
            "enable",
            "disable",
            "logs",
            "logs-recent",
            "update",
            "makefile",
            *per_service_targets,
        ]
    )

    per_service_blocks_text = "\n\n".join(per_service_blocks)

    return f"""# Auto-generated by ros2_systemd_manager
# Re-generate with: make update

SUDO ?= sudo
SCRIPT ?= {script_default}
CONFIG ?=
WORKSPACE_KEY := {workspace_key}
UNITS := {quoted_units}
GENERATED_MK := $(lastword $(MAKEFILE_LIST))

EFFECTIVE_SCRIPT := $(if $(strip $(SCRIPT)),$(SCRIPT),{script_default})
EFFECTIVE_CONFIG := $(if $(strip $(CONFIG)),$(CONFIG),$(firstword $(wildcard ./ros2_services.yaml ./*.yaml)))

.PHONY: {phony_targets}

help:
	@echo \"Targets:\"
	@echo \"  make upgrade                # self-upgrade ros2-systemd-manager via pip\"
	@echo \"  make install                # install unit files only\"
	@echo \"  make apply                  # install + start + enable\"
	@echo \"  make start                  # systemctl start all configured units\"
	@echo \"  make stop                   # systemctl stop all configured units\"
	@echo \"  make restart                # systemctl restart all configured units\"
	@echo \"  make status                 # systemctl status all configured units\"
	@echo \"  make enable                 # systemctl enable all configured units\"
	@echo \"  make disable                # systemctl disable all configured units\"
	@echo \"  make logs                   # follow logs for all configured units\"
	@echo \"  make logs-recent            # show last 200 log lines for all configured units\"
	@echo \"  make <op>-<service>         # op in start/stop/restart/status/enable/disable/logs/logs-recent\"
	@echo \"  make uninstall              # uninstall all configured units\"
	@echo \"  make update                 # stop old + uninstall removed + install/start/enable + refresh generated mk\"
	@echo \"  make makefile               # refresh generated mk only (no systemd changes)\"
	@echo \"  make <target> CONFIG=./file.yaml  # override auto-discovered yaml\"

ensure-config:
	@if [ -z "$(EFFECTIVE_CONFIG)" ]; then \\
		echo "ERROR: no yaml config found in current directory (expected ./ros2_services.yaml or ./*.yaml)."; \\
		exit 1; \\
	fi

upgrade:
	$(EFFECTIVE_SCRIPT) upgrade

install: ensure-config
	$(SUDO) $(EFFECTIVE_SCRIPT) install --config \"$(EFFECTIVE_CONFIG)\" --workspace-key \"$(WORKSPACE_KEY)\"

apply: ensure-config
	$(SUDO) $(EFFECTIVE_SCRIPT) apply --config \"$(EFFECTIVE_CONFIG)\" --workspace-key \"$(WORKSPACE_KEY)\"

uninstall: ensure-config
	$(SUDO) $(EFFECTIVE_SCRIPT) uninstall --config \"$(EFFECTIVE_CONFIG)\" --workspace-key \"$(WORKSPACE_KEY)\"

start:
\t$(SUDO) systemctl start $(UNITS)

stop:
\t$(SUDO) systemctl stop $(UNITS)

restart:
\t$(SUDO) systemctl restart $(UNITS)

status:
\t$(SUDO) systemctl status $(UNITS)

enable:
\t$(SUDO) systemctl enable $(UNITS)

disable:
\t$(SUDO) systemctl disable $(UNITS)

logs:
	$(SUDO) journalctl $(foreach u,$(UNITS),-u $(u)) -f

logs-recent:
	$(SUDO) journalctl $(foreach u,$(UNITS),-u $(u)) -n 200 --no-pager

update: ensure-config
	$(SUDO) $(EFFECTIVE_SCRIPT) update --config \"$(EFFECTIVE_CONFIG)\" --workspace-key \"$(WORKSPACE_KEY)\" --previous-makefile \"$(GENERATED_MK)\"

makefile: ensure-config
	$(EFFECTIVE_SCRIPT) makefile --config \"$(EFFECTIVE_CONFIG)\" --workspace-key \"$(WORKSPACE_KEY)\"

{per_service_blocks_text}
"""


def write_makefile(config: Dict[str, Any], config_path: Path, workspace_key: str) -> Path:
    """Generate (or overwrite) Makefile based on YAML workspace services."""
    workspace_cfg = config["workspaces"][workspace_key]
    services = workspace_cfg.get("services", [])
    unit_names = [svc["unit_name"] for svc in services]

    if not unit_names:
        err(f"workspace {workspace_key} has an empty services list; cannot build Makefile units.")
        sys.exit(1)

    output_path = resolve_makefile_path(config, config_path)
    _migrate_legacy_auto_generated_makefile(config_path.parent, output_path)
    _ensure_main_makefile_includes_fragment(
        config_path.parent, output_path.name)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    makefile_cfg = config.get("makefile", {})
    script_default_raw = str(makefile_cfg.get(
        "command", "ros2-systemd-manager")).strip()
    script_default = script_default_raw or "ros2-systemd-manager"
    content = build_makefile_content(
        script_default=script_default,
        workspace_key=workspace_key,
        unit_names=unit_names,
    )

    output_path.write_text(content, encoding="utf-8")
    log(f"Generated Makefile fragment: {output_path}")
    return output_path
